(package "pinyin-isearch"
         "0.6"
         "pinyin search with isearch")

(website-url "https://github.com/Anoncheg1/pinyin-isearch")
(keywords "lisp" "pinyin-isearch")

(package-file "pinyin-isearch.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
