(package "pinyin-isearch"
         "1.0"
         "Allow to search Chinese pinyin without tones.")

(website-url "https://github.com/Anoncheg1/pinyin-isearch")
(keywords "chinese" "pinyin" "search")

(package-file "pinyin-isearch.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.2")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
