# -*- fill-column: 120; -*-
---
name: check

'on': [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - 30.1
          - 30.2
          - snapshot
    steps:
      - name: Copy repo
        uses: actions/checkout@v5
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'
      - name: Run tests with eask and Make
        run: |
          echo $GITHUB_REF
          make ci |& tee output.log  # stdout & stderr to log file
          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
      - uses: leotaku/elisp-check@master
        with:
          file: '*.el'
          check: melpa
          ignore_warnings: false
          warnings_as_errors: true
