# -*- fill-column: 120; -*-
# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.
---
name: melpazoid
'on': [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]
        emacs_version:
          # - 26.1
          # - 26.2
          # - 26.3
          # - 27.1
          # - 27.2
          - 28.1
          # - 28.2
          - 29.1
          # - 29.2
          # - 29.3
          - 29.4
          - 30.1
          - release-snapshot
    steps:

      # - name: Install
      #   run: |
      #     python -m pip install --upgrade pip
      #     sudo apt-get install emacs-nox && emacs --version
      #     git clone https://github.com/riscy/melpazoid.git ~/melpazoid
      #     pip install ~/melpazoid

      - name: Install Emacs
        uses: purcell/setup-emacs@v8.0
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Copy repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Tests1 - pinyin
        run: |
         emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el -l pinyin-isearch-pinyin.el -l pinyin-isearch-pinyin-tests.el -f ert-run-tests-batch-and-exit

      - name: Tests2 - chars
        run: |
         emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el -l pinyin-isearch-chars.el -l pinyin-isearch-chars-tests.el -f ert-run-tests-batch-and-exit

      - name: Tests3 - main
        run: |
         emacs -Q --batch --no-site-file -l pinyin-isearch-loaders.el  -l pinyin-isearch-chars.el -l pinyin-isearch-pinyin.el -l pinyin-isearch.el -l pinyin-isearch-main-tests.el -f ert-run-tests-batch-and-exit

      - name: Run Makefile
        run: |
          make test
          [ $? -ne 0 ] && { echo "Make test command failed, failing workflow"; exit 1; }
          make checkdoc
          [ $? -ne 0 ] && { echo "Make checkdoc command failed, failing workflow"; exit 1; }
          make lint |& tee output.log # always exit with 1 error code
          if grep -q '[0-9] issue found:' output.log ; then
            echo GREP 10 lines ----------------------:
            grep -A 10 '[0-9] issue found:' output.log
            echo "Error detected, failing workflow" ; exit 1
          fi

      - name: Set up Python 3.12 for melpazoid
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install melpazoid
        run: |
          python -m pip install --upgrade pip
          # sudo apt-get install emacs-nox && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid

      - name: Melpazoid check
        env:
          LOCAL_REPO: ${{ github.workspace }}
          # RECIPE is your recipe as written for MELPA:
          RECIPE: (pinyin-isearch :fetcher github :repo "Anoncheg1/pinyin-isearch")
          # set this to false (or remove it) if the package isn't on MELPA:
          EXIST_OK: true
        run: |
          echo $GITHUB_REF
          make -C ~/melpazoid |& tee output.log
          make_exit=${PIPESTATUS[0]}
          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
          if grep -q "Warning" output.log ; then
            echo "Warnings detected, failing workflow" ; exit 1
          fi
          if grep -q ': error: ' output.log ; then
            echo "Error detected, failing workflow" ; exit 1
          fi
          if grep -q ' with [melpazoid]' output.log ; then
            echo "Melpazoid warning detected, failing workflow" ; exit 1
          fi
          if grep -q ' with package-lint ' output.log ; then
            echo "Checkdoc warning detected, failing workflow" ; exit 1
          fi
          if grep -q ' with checkdoc ' output.log ; then
            echo "Checkdoc warning detected, failing workflow" ; exit 1
          fi
